name: primus_dart
description: Primus implementation for dart.
author: Richard Soderman <richard.soderman@gmail.com>
homepage: https://github.com/richie-south/primus-dart
version: 0.0.1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  web_socket_channel: ^1.1.0
  json_isolate: 0.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.5
